spring.application.name=order-service
server.port=8084

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/buy01}
spring.data.mongodb.auto-index-creation=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Other services
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}
user.service.url=${USER_SERVICE_URL:http://localhost:8081}

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

